services:
  auth-postgres:
    image: "postgres:16-alpine"
    container_name: "auth-postgres"
    env_file:
      - .env
    ports:
      - "25432:5432"
    volumes:
      - auth-postgres:/var/lib/postgresql/data

volumes:
  auth-postgres:
    name: duo-auth-postgres
