services:
  game-postgres:
    image: "postgres:16-alpine"
    container_name: "game-postgres"
    env_file:
      - .env
    ports:
      - "25433:5432"
    volumes:
      - game-postgres:/var/lib/postgresql/data

volumes:
  game-postgres:
    name: duo-game-postgres
