name: duo-app

services:
  api:
    image: ghcr.io/voinovvladyslav/duo:${IMAGE_TAG:-latest}
    network_mode: host
    env_file: .env
    volumes:
      - ${API_KEY_PATH:-/opt/duo/keys/api/}:/keys/:ro
    restart: unless-stopped
    command: >
      gunicorn -c services/api/gunicorn_conf.py 
      --bind ${GUNICORN_BIND:-0.0.0.0:8000}
      -w 1
      services.api.main:app 

  auth:
    image: ghcr.io/voinovvladyslav/duo:${IMAGE_TAG:-latest}
    network_mode: host
    env_file: .env
    environment:
      - POSTGRES_HOST=${AUTH_POSTGRES_HOST}
      - POSTGRES_PORT=${AUTH_POSTGRES_PORT}
      - POSTGRES_DB=${AUTH_POSTGRES_DB}
      - POSTGRES_USER=${AUTH_POSTGRES_USER}
      - POSTGRES_PASSWORD=${AUTH_POSTGRES_PASSWORD}
    volumes:
      - ${AUTH_KEY_PATH:-/opt/duo/keys/auth/}:/keys/:ro
    restart: unless-stopped
    command: python -m services.auth

  game:
    image: ghcr.io/voinovvladyslav/duo:${IMAGE_TAG:-latest}
    network_mode: host
    env_file: .env
    environment:
      - POSTGRES_HOST=${GAME_POSTGRES_HOST}
      - POSTGRES_PORT=${GAME_POSTGRES_PORT}
      - POSTGRES_DB=${GAME_POSTGRES_DB}
      - POSTGRES_USER=${GAME_POSTGRES_USER}
      - POSTGRES_PASSWORD=${GAME_POSTGRES_PASSWORD}
    volumes:
      - ${GAME_KEY_PATH:-/opt/duo/keys/game/}:/keys/:ro
    restart: unless-stopped
    command: python -m services.game

