"""empty message

Revision ID: 955d762b14f2
Revises: b8ab88e9cae8
Create Date: 2026-04-09 17:03:51.708876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '955d762b14f2'
down_revision: Union[str, Sequence[str], None] = 'b8ab88e9cae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'player2',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('game', 'current_player',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'current_player',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('game', 'player2',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
