name: checks-backend

on:
  push:
    branches: [main]
    tags: ['*']
    paths-ignore: ['services/ui/**', '.github/workflows/frontend-ci.yml']
  pull_request:
    branches: [main]
    paths-ignore: ['services/ui/**', '.github/workflows/frontend-ci.yml']

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: set up uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true  # caches based on uv.lock automatically

      - name: install dependencies
        run: uv sync --frozen
      
      - name: generate proto
        run: |
          cp ./proto/*.proto ./generated/
          uv run python \
            -m grpc_tools.protoc \
            -I . \
            --python_out=. \
            --grpc_python_out=. \
            --mypy_out=. \
            --mypy_grpc_out=. \
            ./generated/*.proto
          rm ./generated/*.proto


      - name: format
        run: uv run ruff format --check

      - name: lint
        run: uv run ruff check

      - name: type check
        run: uv run basedpyright

      - name: tests
        run: uv run pytest
      

  build:
    runs-on: ubuntu-latest
    needs: [checks]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v6

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v4

      - name: login to ghcr.io
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: voinovvladyslav
          password: ${{ secrets.CONTAINER_REGISTRY_ACCESS_TOKEN }}

      - name: build the image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: deploy/Dockerfile
          push: true
          tags: ghcr.io/voinovvladyslav/duo:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v5

      - name: setup ssh key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: sync files
        run: |
          rsync -az \
          deploy/compose.yml \
          ${{ secrets.SERVER_USER }}@${{secrets.SERVER_HOST }}:/opt/duo/

      - name: deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          script: |
            cd /opt/duo/
            IMAGE_TAG=${{ github.ref_name }} docker compose pull
            IMAGE_TAG=${{ github.ref_name }} docker compose down
            IMAGE_TAG=${{ github.ref_name }} docker compose run --rm -rf auth alembic -c ./services/auth/alembic.ini upgrade head
            IMAGE_TAG=${{ github.ref_name }} docker compose run --rm -rf game alembic -c ./services/game/alembic.ini upgrade head
            IMAGE_TAG=${{ github.ref_name }} docker compose up -d
            docker image prune -af

