name: checks-backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  checks-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true  # caches based on uv.lock automatically

      - name: Install dependencies
        run: uv sync --frozen
      
      - name: Generate Proto
        run: |
          cp ./proto/*.proto ./generated/
          uv run python \
            -m grpc_tools.protoc \
            -I . \
            --python_out=. \
            --grpc_python_out=. \
            --mypy_out=. \
            --mypy_grpc_out=. \
            ./generated/*.proto
          rm ./generated/*.proto


      - name: Format
        run: uv run ruff format --check

      - name: Lint
        run: uv run ruff check

      - name: Type check
        run: uv run basedpyright

      - name: Tests
        run: uv run pytest

